parameters:
  - title: application name
    description: Name of your application
    key: APP_NAME
    default: gin-vue
    required: true
  - title: kubeconfig
    description: Path to your kubeconfig file
    key: KUBECONFIG
    type: "path"
    default: ~/.kube/config
    required: true
  - title: github personal access token
    description: Your github access token
    key: GITHUB_TOKEN
    type: "secret"
    required: true
  - title: github organization
    description: Which github organization do you want to use?
    key: ORGANIZATION
    required: true
  - title: github repository visibility
    default: private
    description: Which kind of repository do you want, public or private ?
    key: REPO_VISIBILITY
