parameters:
  - title: applicationName
    description: Name of your application.
    key: APP_NAME
    default: gin-vue-app
    required: true
  - title: kubeConfig
    description: Path to your kubeconfig file.
    key: KUBECONFIG
    default: ~/.kube/config
    required: true
  - title: githubToken
    description: Access token of your github account.
    key: GITHUB_TOKEN
    required: true
  - title: organization
    description: Github organization of your developing team.
    key: ORGANIZATION