parameters:
  - title: kubeConfig
    description: Path to your kubeconfig file
    key: KUBECONFIG
    type: "path"
    default: ~/.kube/config
    required: true

  - title: githubToken
    description: Your github access token
    key: GITHUB_TOKEN
    type: "secret"
    required: true
