actions:
  up:
    args:
      service:
        - name: forkmain-backend
          type: backend
          url: https://github.com/lyzhang1999/forkmain-backend
          # set env
          env: 
            - name: KEY
              value: VALUE
          # add any values key
          extra:
            env2:
              - name: KEY2
                value: VALUE2
              - name: KEY3
                value: VALUE3
        - name: forkmain-frontend
          type: frontend
          url: https://github.com/lyzhang1999/forkmain-frontend
          env: 
            - name: KEY
              value: VALUE
      deploy:
        name: forkmain-deploy
        url: https://github.com/lyzhang1999/forkmain-deploy
      forkenv:
        name: bug-fix
        from: main
        domain: bug-fix.hello-world36.h8r.site
      scm:
        name: github
        type: github
        organization: h8r-dev