name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-stack:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        stack_dir:
          # add stack directory here if you want to test
          - gin-next
          - sample
    runs-on: ${{ matrix.os }}
    env:
      stack_dir: ${{ matrix.stack_dir }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Docker on macOS
        if: startsWith(matrix.os, 'macos' )
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: 20.10
          docker_channel: stable
          docker_buildx: false
          docker_cli_experimental: disable

      - name: Create K8s Kind Cluster on macOS
        if: startsWith(matrix.os, 'macos' )
        run: |
          brew install kind
          kind create cluster --config ./scripts/kind-config.yaml --wait 2m

      - name: Create Kind Cluster
        if: startsWith(matrix.os, 'ubuntu' )
        uses: helm/kind-action@deab45fc8df9de5090a604e8ec11778eea7170bd
        with:
          config: "./scripts/kind-config.yaml"
          version: "v0.12.0"
          kubectl_version: "v1.23.4"

      - name: Install Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

      - name: Install hln
        run: |
          curl -L https://dl.h8r.io/hln/install.sh | sh
          sudo mv bin/hln /usr/local/bin/hln
          hln version

      - name: hln init
        run: |
          hln init

      - name: Stacks Cue Vendor
        run: |
          make vendor

      - name: hln up
        id: hln_up
        env:
          STACK_DIR: ${{ env.stack_dir }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          ORGANIZATION: heigliner-robot
          HLN_LOG_LEVEL: "debug"
          HLN_LOG_FORMAT: "plain"
        run: |
          export APP_NAME="$STACK_DIR-$(date +'%Y-%m-%dt%H-%M-%S' -d '+8 hour')"
          echo "::set-output name=app_name::$APP_NAME"
          hln up --dir $STACK_DIR

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run Ginkgo Tests
        env:
          APP_NAME: ${{ steps.hln_up.outputs.app_name }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          ORGANIZATION: heigliner-robot
          STACK_DIR: ${{ env.stack_dir }}
        run: |
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
          ginkgo $STACK_DIR/test
